In [416]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [451]:
data = pd.read_csv("Housing.csv")

In [453]:
X = data[['area','bedrooms', 'bathrooms']].values
y = data['price'].values

In [455]:
X

array([[7420,    4,    2],
       [8960,    4,    4],
       [9960,    3,    2],
       ...,
       [3620,    2,    1],
       [2910,    3,    1],
       [3850,    3,    1]], dtype=int64)

In [457]:
y

array([13300000, 12250000, 12250000, 12215000, 11410000, 10850000,
       10150000, 10150000,  9870000,  9800000,  9800000,  9681000,
        9310000,  9240000,  9240000,  9100000,  9100000,  8960000,
        8890000,  8855000,  8750000,  8680000,  8645000,  8645000,
        8575000,  8540000,  8463000,  8400000,  8400000,  8400000,
        8400000,  8400000,  8295000,  8190000,  8120000,  8080940,
        8043000,  7980000,  7962500,  7910000,  7875000,  7840000,
        7700000,  7700000,  7560000,  7560000,  7525000,  7490000,
        7455000,  7420000,  7420000,  7420000,  7350000,  7350000,
        7350000,  7350000,  7343000,  7245000,  7210000,  7210000,
        7140000,  7070000,  7070000,  7035000,  7000000,  6930000,
        6930000,  6895000,  6860000,  6790000,  6790000,  6755000,
        6720000,  6685000,  6650000,  6650000,  6650000,  6650000,
        6650000,  6650000,  6629000,  6615000,  6615000,  6580000,
        6510000,  6510000,  6510000,  6475000,  6475000,  6440

In [459]:
def normalize_features(X):
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    return (X - mean) / std, mean, std

X_norm, X_mean, X_std = normalize_features(X)

In [461]:
def hypothesis(X, w):
    return np.dot(X, w)

In [463]:
def compute_cost(X, y, w):
    m = len(y)
    predictions = hypothesis(X, w)
    cost = (1/(2*m)) * np.sum((predictions - y) ** 2)
    return cost

In [515]:
def gradient_descent_step(X, y, w, learning_rate):
    m = len(y)
    predictions = hypothesis(X, w)  # X має містити bias
    errors = predictions - y
    gradient = (1/m) * np.dot(X.T, errors)
    
    return w - learning_rate * gradient

In [523]:
def linear_regression(X, y, learning_rate, iterations):
    w = np.zeros(X.shape[1])  # ініціалізуємо ваги нулями

    for i in range(iterations):
        w = gradient_descent_step(X, y, w, learning_rate)
        cost = compute_cost(X, y, w)
        print(w)

    return w

In [525]:
learning_rate = 0.01
iterations = 1000

# Знаходимо найкращі параметри
w, cost_history = linear_regression(X, y, learning_rate, iterations)
w

[2.67229201e+08 1.46390263e+05 6.61666767e+04]
[-8.34523562e+13 -4.14599319e+10 -1.82670843e+10]
[2.60612157e+19 1.29474706e+16 5.70460611e+15]
[-8.13861939e+24 -4.04334689e+21 -1.78148320e+21]
[2.54159769e+30 1.26269096e+27 5.56336813e+26]
[-7.93711869e+35 -3.94323934e+32 -1.73737619e+32]
[2.47867132e+41 1.23142852e+38 5.42562700e+37]
[-7.74060686e+46 -3.84561032e+43 -1.69436122e+43]
[2.41730293e+52 1.20094009e+49 5.29129615e+48]
[-7.54896038e+57 -3.75039844e+54 -1.65241123e+54]
[2.35745393e+63 1.17120651e+60 5.16029114e+59]
[-7.36205880e+68 -3.65754388e+65 -1.61149986e+65]
[2.29908670e+74 1.14220909e+71 5.03252963e+70]
[-7.17978463e+79 -3.56698827e+76 -1.57160141e+76]
[2.24216457e+85 1.11392961e+82 4.90793132e+81]
[-7.00202332e+90 -3.47867469e+87 -1.53269078e+87]
[2.18665174e+96 1.08635029e+93 4.78641788e+92]
[-6.82866313e+101 -3.39254762e+098 -1.49474352e+098]
[2.13251334e+107 1.05945379e+104 4.66791294e+103]
[-6.65959509e+112 -3.30855294e+109 -1.45773579e+109]
[2.07971533e+118 1.03

C:\Users\4atty\AppData\Local\Temp\ipykernel_24648\3435018892.py:4: RuntimeWarning: overflow encountered in square
  cost = (1/(2*m)) * np.sum((predictions - y) ** 2)
C:\Users\4atty\AppData\Local\Temp\ipykernel_24648\3338230767.py:7: RuntimeWarning: invalid value encountered in subtract
  return w - learning_rate * gradient


ValueError: too many values to unpack (expected 2)

In [489]:
def normal_equation(X, y):
    return np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

w_normal = normal_equation(X, y)
print(f"Аналітичне рішення (Normal Equation) параметри: {w_normal}")

Аналітичне рішення (Normal Equation) параметри: [3.72448352e+02 3.68974672e+05 1.37031315e+06]


In [491]:
def sklearn_regression(X, y):
    model = LinearRegression()
    model.fit(X, y)
    return model.coef_, model.intercept_

In [493]:
sklearn_regression(X, y)

(array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06]), -173171.6076326361)

In [438]:
learning_rate = 0.1
iterations = 100000

# Навчання моделі
w, cost_history = linear_regression(X_norm, y, learning_rate, iterations)

w

array([821214.14349519, 299983.57107963, 695808.52272537])

In [585]:
def mse(y_true, y_pred):
    return np.mean(np.sum((y_true - y_pred) ** 2))
    

In [587]:


# Градієнтний спуск
def grad_descent(X, y, iter=3000, lr=0.001, stopping_threshold=0.001):
    m, n = X.shape
    w = np.random.rand(n) * 0.01
    prev_cost = None

    for i in range(iter):
        y_pred = X.dot(w)
        cost = mse(y, y_pred)
        
        if np.isnan(cost) or np.isinf(cost):
            print("Cost is NaN or inf, exiting...")
            break
            
        if prev_cost is not None and abs(cost - prev_cost) <= stopping_threshold:
            break

        prev_cost = cost

        gradient = (1/m) * (X.T.dot(y - y_pred))  # Градієнт
        w -= lr * gradient  # Оновлення ваг

        print(f'Iteration {i+1}: Cost {cost}, Weights: {w}')

    return w

In [589]:
weights = grad_descent(X, y)
print("Отримані ваги:", weights)

Iteration 1: Cost 1.428652718584006e+16, Weights: [-2.67229076e+07 -1.46390132e+04 -6.61665892e+03]
Iteration 2: Cost 1.21548428621042e+25, Weights: [-8.34581963e+11 -4.14631331e+08 -1.82685314e+08]
Iteration 3: Cost 1.1854741238119855e+34, Weights: [-2.60639576e+16 -1.29488328e+13 -5.70520628e+12]
Iteration 4: Cost 1.156204908926075e+43, Weights: [-8.13976235e+20 -4.04391473e+17 -1.78173338e+17]
Iteration 5: Cost 1.1276583474687218e+52, Weights: [-2.54204416e+25 -1.26291277e+22 -5.56434541e+21]
Iteration 6: Cost 1.099816597212866e+61, Weights: [-7.93879258e+29 -3.94407095e+26 -1.73774260e+26]
Iteration 7: Cost 1.0726622564539109e+70, Weights: [-2.47928139e+34 -1.23173160e+31 -5.42696239e+30]
Iteration 8: Cost 1.0461783531332721e+79, Weights: [-7.74278474e+38 -3.84669231e+35 -1.69483794e+35]
Iteration 9: Cost 1.0203483342304706e+88, Weights: [-2.41806823e+43 -1.20132030e+40 -5.29297133e+39]
Iteration 10: Cost 9.951560554171296e+96, Weights: [-7.55161631e+47 -3.75171794e+44 -1.65299259e

C:\Users\4atty\AppData\Local\Temp\ipykernel_24648\300550005.py:2: RuntimeWarning: overflow encountered in square
  return np.mean(np.sum((y_true - y_pred) ** 2))


In [547]:
print("NaN в X:", np.isnan(X).any())
print("Безмежні в X:", np.isinf(X).any())
print("NaN в y:", np.isnan(y).any())
print("Безмежні в y:", np.isinf(y).any())

NaN в X: False
Безмежні в X: False
NaN в y: False
Безмежні в y: False
